// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbXsXi6TTbgVkEo5bzDq0mj1lseYrycZY',
    appId: '1:636589956498:android:a4dfcd3b6fc3dc2c89f54b',
    messagingSenderId: '636589956498',
    projectId: 'ecoclassify-c0bad',
    storageBucket: 'ecoclassify-c0bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlz6DytuxSiKVg62qUJNBEoXchRLJhosE',
    appId: '1:636589956498:ios:fc3a866a1768d23189f54b',
    messagingSenderId: '636589956498',
    projectId: 'ecoclassify-c0bad',
    storageBucket: 'ecoclassify-c0bad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlz6DytuxSiKVg62qUJNBEoXchRLJhosE',
    appId: '1:636589956498:ios:fc3a866a1768d23189f54b',
    messagingSenderId: '636589956498',
    projectId: 'ecoclassify-c0bad',
    storageBucket: 'ecoclassify-c0bad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEGSWn0_kP2twG4AkiJKWRjVdXHC8-d8M',
    appId: '1:636589956498:web:64680cd3cd11460589f54b',
    messagingSenderId: '636589956498',
    projectId: 'ecoclassify-c0bad',
    authDomain: 'ecoclassify-c0bad.firebaseapp.com',
    storageBucket: 'ecoclassify-c0bad.firebasestorage.app',
    measurementId: 'G-S3GPV4TEJH',
  );
}
